---
title: "Binomial"
author: "Curso de Estadística Descriptiva"
date: "4/2/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

La binomial da el nº de éxitos esperados al hacer el experimento n veces. Bernoulli sería como una binomial de n = 1

## Función de densidad
Sea $X = B(n = 30, p = 0.6)$,

TODO: escribir la FDens y la FDistr

## En `R`

```{r}
library(Rlab)
n = 30
p = 0.6
plot(0:n, dbinom(0:n, size = n, prob = p))
#probabilidad de 0 a 30 éxitos, haciendo el experimento 30 veces con una probalidad de 0.6
plot(0:n, pbinom(0:n, size = n, prob = p))
qbinom(0.5, n, p)
qbinom(0.25, n, p)
hist(rbinom(100000, n, p), breaks = 0:30)
#nº de éxitos esperados al hacer 100000 veces el experimento de lanzar la moneda 30 veces (por ejemplo) con una probabilidad de éxito del 0.6 (por ejemplo cara, pero sería el valor que consideremos éxito)
```

## En Python

```{python}
from scipy.stats import binom 
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots(1,1)
n = 7
p = 0.4

mean, var, skew, kurt = binom.stats(n, p, moments = 'mvsk')
#son los 4 estadísticos que devuelve la función stats

print("Media %f"%mean)
print("Varianza %f"%var)
print("Sesgo %f"%skew)
print("Curtosis %f"%kurt)


x = np.arange(0, n+1) #valores del eje x
ax.plot(x, binom.pmf(x, n, p), 'bo', ms = 8, label = "Función de densidad de B(7,0.4)")
ax.vlines(x, 0, binom.pmf(x,n,p), colors = 'b', lw = 4, alpha = 0.5)

rv = binom(n,p)
ax.vlines(x,0, rv.pmf(x), colors = 'k', linestyles='--', lw = 1, label = "Distribución teórica")

ax.legend(loc = 'best', frameon = False)

plt.show()


fix, ax = plt.subplots(1,1)
r = binom.rvs(n, p, size = 10000)
ax.hist(r, bins = n)
plt.show()
```

